version: "3.9"
services:
  mysql:
    container_name: mysql
    image: mysql/mysql-server
    ports:
      - 3306:3306
    volumes:
      - .:/app
      - ./scripts/init_mysql.sh:/docker-entrypoint-initdb.d/init_mysql.sh
      - ./configs/mysql/my.cnf:/etc/my.cnf
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - ROOT_USER=${ROOT_USER}
      - DB_HOST=localhost
      - APP_USER=${APP_USER}
      - APP_PWD=${APP_PWD}

  app:
    depends_on:
      - mysql
    image: matrix_quiz
    build:
      context: .
      args:
        - JAR_FILE=/app/app/build/libs/*.jar
    container_name: app
    ports:
      - "8081:8080"
    environment:
      - APP_USER=${APP_USER}
      - APP_PWD=${APP_PWD}
    command:
      - "--spring.datasource.username=${APP_USER}"
      - "--spring.datasource.password=${APP_PWD}"
      - "--spring.datasource.url=jdbc:mysql://mysql:3306/matrix_quiz"
